AllCops:
  Exclude:
    - "app/view/**/*"
    - "db/schema.rb"
    - "spec/rails_helper.rb"
  TargetRubyVersion: 2.5.1

Documentation:
  Enabled: false
Layout::AlignHash:
  Enabled: false
Layout/SpaceBeforeFirstArg:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": ()
    "%w": ()
    "%W": ()
