default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8

development:
  <<: *default
  database: bottle-search_dev
  username: postgres
  password:

test:
  <<: *default
  database: bottle-search_test
  username: postgres
  password:

production:
  <<: *default
  database: bottle-search_prod
