default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8

development:
  <<: *default
  database: bottle-search_dev
  username: root
  password:

test:
  <<: *default
  database: bottle-search_test
  username: root
  password:

production:
  <<: *default
  database: bottle-search_prod
